#!/bin/sh

OUTPUT_DIR=/tmp

#scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P 33333 "$@" mich@localhost:/tmp/
scp -P 33333 "$@" mich@localhost:${OUTPUT_DIR}
for file in "$@"; do
	ssh mich@localhost -p 33333 'open '"${OUTPUT_DIR}"'/'"$file"''
done

exit
